# Generated by Django 5.0.6 on 2025-10-24 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(upload_to='banners/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ConfigPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_igreja', models.CharField(default='Assembleia de Deus Só Jesus Salva', max_length=150, verbose_name='Nome da Igreja')),
                ('pastor', models.CharField(blank=True, default='Pastora Angélica Coutinho dos Santos', max_length=100, null=True, verbose_name='Pastor Responsável')),
                ('mensagem_boas_vindas', models.TextField(blank=True, help_text='Texto exibido na página inicial do portal.', null=True, verbose_name='Mensagem de boas-vindas')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo da Igreja')),
                ('plano_fundo', models.ImageField(blank=True, help_text='Imagem usada como plano de fundo do site.', null=True, upload_to='config/', verbose_name='Plano de Fundo')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Portal',
                'verbose_name_plural': 'Configurações do Portal',
            },
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Dízimo', 'Dízimo'), ('Oferta', 'Oferta'), ('Outros', 'Outros')], default='Dízimo', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribuinte', models.CharField(blank=True, max_length=100, null=True)),
                ('identificacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ministerio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('recibo', models.FileField(blank=True, null=True, upload_to='recibos/')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('batizado', models.BooleanField(default=False)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
            },
        ),
        migrations.CreateModel(
            name='Obreiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do obreiro')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo/Função')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Obreiro',
                'verbose_name_plural': 'Obreiros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_visita', models.DateField(default=django.utils.timezone.now)),
                ('frequenta_igreja', models.BooleanField(default=False)),
                ('cristao', models.BooleanField(default=False)),
                ('igreja_origem', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='EscalaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culto', models.CharField(default='Culto de Domingo', max_length=100, verbose_name='Culto')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Culto')),
                ('tarefa', models.CharField(blank=True, max_length=150, null=True, verbose_name='Função / Tarefa')),
                ('local', models.CharField(blank=True, max_length=150, null=True, verbose_name='Local do Culto')),
                ('obreiros', models.ManyToManyField(blank=True, to='core.obreiro', verbose_name='Obreiros Escalados')),
            ],
            options={
                'verbose_name': 'Escala de Culto',
                'verbose_name_plural': 'Escala de Cultos',
                'ordering': ['-data'],
            },
        ),
    ]
