# Generated by Django 5.0.6 on 2025-10-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_igreja', models.CharField(max_length=200)),
                ('pastor', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('mensagem_boas_vindas', models.CharField(default='Seja bem-vindo(a) ao nosso portal!', max_length=255)),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='fundos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('banner_titulo', models.CharField(blank=True, default='', max_length=150)),
                ('banner_subtitulo', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': '⚙️ Configuração do Sistema',
                'verbose_name_plural': '⚙️ Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('batizado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Ministérios',
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Missões',
            },
        ),
        migrations.CreateModel(
            name='Obreiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cargo', models.CharField(choices=[('Diácono', 'Diácono'), ('Presbítero', 'Presbítero'), ('Cooperador', 'Cooperador'), ('Evangelista', 'Evangelista'), ('Pastor', 'Pastor')], max_length=30)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Obreiros',
            },
        ),
        migrations.DeleteModel(
            name='ConfiguracaoSite',
        ),
        migrations.AlterModelOptions(
            name='contribuicao',
            options={'verbose_name_plural': 'Contribuições'},
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='escalaservico',
            options={'ordering': ['-data'], 'verbose_name': 'Escala de Serviço', 'verbose_name_plural': 'Escalas de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ['-data_visita'], 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.RenameField(
            model_name='escalaservico',
            old_name='data_servico',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='faz_parte_de_igreja',
            new_name='frequenta_igreja',
        ),
        migrations.RemoveField(
            model_name='contribuicao',
            name='descricao_outros',
        ),
        migrations.RemoveField(
            model_name='contribuicao',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='escalaservico',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='escalaservico',
            name='nome_obreiro',
        ),
        migrations.RemoveField(
            model_name='escalaservico',
            name='observacao',
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='contribuinte',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Contribuinte'),
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='outros_destino',
            field=models.CharField(blank=True, default='', help_text="Destino/descrição para 'Outros'.", max_length=200),
        ),
        migrations.AddField(
            model_name='escalaservico',
            name='culto',
            field=models.CharField(default='Outros', help_text='Ex.: Culto de Doutrina, EBD, Santa Ceia…', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='tipo',
            field=models.CharField(choices=[('Dízimo', 'Dízimo'), ('Oferta', 'Oferta'), ('Outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='data_visita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='igreja_origem',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='departamento',
            name='ministerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ministerio'),
        ),
        migrations.AddField(
            model_name='escalaservico',
            name='obreiros',
            field=models.ManyToManyField(blank=True, to='core.obreiro'),
        ),
    ]
