# Generated by Django 5.0.6 on 2025-10-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalaservico',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.CreateModel(
            name='EscalaObreiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Função no Culto')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.escalaservico')),
                ('obreiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obreiro')),
            ],
            options={
                'verbose_name': 'Obreiro na Escala',
                'verbose_name_plural': 'Obreiros nas Escalas',
                'ordering': ['escala', 'obreiro'],
            },
        ),
    ]
