# Generated by Django 5.0.6 on 2025-10-24 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalaservico',
            options={'ordering': ['-data'], 'verbose_name': 'Escala de Culto', 'verbose_name_plural': 'Escala de Cultos'},
        ),
        migrations.AddField(
            model_name='escalaservico',
            name='local',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Local do Culto'),
        ),
        migrations.AlterField(
            model_name='escalaservico',
            name='culto',
            field=models.CharField(default='Culto de Domingo', max_length=100, verbose_name='Culto'),
        ),
        migrations.AlterField(
            model_name='escalaservico',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Culto'),
        ),
        migrations.AlterField(
            model_name='escalaservico',
            name='obreiros',
            field=models.ManyToManyField(blank=True, to='core.obreiro', verbose_name='Obreiros Escalados'),
        ),
        migrations.AlterField(
            model_name='escalaservico',
            name='tarefa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Função / Tarefa'),
        ),
    ]
