# Generated by Django 5.0.6 on 2026-02-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_escalaservico_observacoes_escalaobreiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Nota')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Bloco de Notas',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
