# Generated by Django 5.0.6 on 2026-02-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Anotação Administrativa', max_length=150, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Anotação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Anotação do Admin',
                'verbose_name_plural': 'Anotação do Admin',
            },
        ),
    ]
