# Generated by Django 5.0.6 on 2026-04-28 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_anotacaoadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoOracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('pedido', models.TextField(verbose_name='Pedido')),
                ('confidencial', models.BooleanField(default=True, verbose_name='Confidencial')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ACOMPANHAMENTO', 'Em acompanhamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pedido de Oração',
                'verbose_name_plural': 'Pedidos de Oração',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='configportal',
            name='chave_igreja',
            field=models.SlugField(blank=True, help_text='Identificador único para versões white-label (ex: igreja-central).', max_length=80, null=True, unique=True, verbose_name='Chave da Igreja'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='cor_destaque',
            field=models.CharField(default='#f4b942', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal, ex: #f4b942', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor de Destaque'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='cor_fundo',
            field=models.CharField(default='#f4f7fb', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal, ex: #f4f7fb', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor de Fundo'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='cor_primaria',
            field=models.CharField(default='#0f4c81', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal, ex: #0f4c81', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Primária'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='cor_secundaria',
            field=models.CharField(default='#1f7a8c', max_length=7, validators=[django.core.validators.RegexValidator(message='Use formato hexadecimal, ex: #1f7a8c', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='dominio_oficial',
            field=models.CharField(blank=True, help_text='Ex: adsjs.com.br', max_length=120, null=True, verbose_name='Domínio Oficial'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail de Contato'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='estado',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='nome_sistema',
            field=models.CharField(default='ChurchManager Pro', help_text='Nome comercial exibido no painel e no login.', max_length=120, verbose_name='Nome do Sistema'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='recebe_novas_igrejas',
            field=models.BooleanField(default=True, help_text='Marque para sinalizar esta instalação como pronta para vender para outras igrejas.', verbose_name='Instância comercial (revenda ativa)'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='slogan_sistema',
            field=models.CharField(blank=True, default='Gestão inteligente para igrejas', max_length=180, null=True, verbose_name='Slogan do Sistema'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone de Contato'),
        ),
        migrations.AddField(
            model_name='configportal',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
