# Generated by Django 5.0.6 on 2026-04-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedidooracao_configportal_chave_igreja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configportal',
            name='whatsapp_pedidos_oracao',
            field=models.CharField(blank=True, help_text='Número com DDI. Ex: 5521999999999', max_length=25, null=True, verbose_name='WhatsApp para Pedidos de Oração'),
        ),
    ]
