# Generated by Django 5.0.6 on 2026-04-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_configportal_whatsapp_pedidos_oracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configportal',
            name='agenda_cultos',
            field=models.TextField(blank=True, help_text='Informe uma linha por culto. Exemplo:\nQuarta-feira • 19:30 • Culto de Ensino\nDomingo • 09:00 • Escola Bíblica\nDomingo • 18:00 • Culto da Família', null=True, verbose_name='Dias e horários de culto'),
        ),
    ]
